name: GitHub Actions
run-name: sonos configuration
on:
   schedule:
     - cron: "15 4 * * *"
jobs:
  Sonos-Configuration:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm install
      - name: run sonos configuration
        run: npm start
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          LOGIN: ${{ secrets.LOGIN }}
          PASSWORD: ${{ secrets.PASSWORD }}