name: GitHub Actions Demo
run-name: sonos configuration
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: setupo node
        uses: actions/setup-node@v6
        with:
          node-version: 'latest'
      - name: Install dependencies
        run: npm install
      - name: run sonos configuration
        run: npm start